version: '3.7'


x-db-config: &db-config
  DATABASE_NAME: ${DATABASE_NAME}
  DATABASE_HOST: ${DATABASE_HOST}
  DATABASE_PORT: ${DATABASE_PORT}
  DATABASE_USER: ${POSTGRES_USER}
  DATABASE_PASSWORD: ${POSTGRES_PASSWORD}

services:
  api:
    build: .
    restart: unless-stopped
    ports:
      - 8000:8000
    networks:
      - mynetwork
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - ./exbot:/app:cached
      - ~/.ssh:/root/.ssh
      - ~/.bash_history:/root/.bash_history
    command: uvicorn api.main:app --host 0.0.0.0 --reload

  bot:
    build: .
    restart: unless-stopped
    depends_on:
      - db
      - api
    volumes:
      - ./exbot:/app:cached
      - ~/.ssh:/root/.ssh
      - ~/.bash_history:/root/.bash_history
    env_file:
      - .env
    networks:
      - mynetwork
    command: python run.py

  db:
    image: postgres:15.2-alpine
    restart: unless-stopped
    ports:
      - 5432:5432
    networks:
      - mynetwork
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

networks:
  mynetwork:
    driver: bridge
