"""Admin init

Revision ID: 96edf433a72e
Revises: 
Create Date: 2023-07-08 10:07:14.809945

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "96edf433a72e"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
